pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh '''
                    echo 'Building the demo ngnix docker image..'
                    ls -la
                    pwd
                    docker build -t nginx -t .
             '''  
            }
        }
        stage('Test') {
            steps {
                echo 'Sonarqube Testing In Progress..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying to Amazon ECS....'
            }
        }
    }
}
