pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh '''
                    cd jenkins-cicd/
                    echo 'Building the demo ngnix docker image..'
                    ls -la
                    pwd
                    docker build -t ngnix1 .
             '''  
            }
        }
        stage('Test') {
            steps {
                echo 'Code Quality and Code Security Testing using Sonarqube.. '
                echo 'Testing in progress..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying to Amazon ECS....'
            }
        }
    }
}
