pipeline {
        environment {
            REGION='us-east-1'
            CLUSTER='avv-cicd-demo'
            AWS_ACCOUNT='250155391967'
            SERVICE_NAME='avv-jenkins-cicd-demo'
            TASKDEF_NAME='avv-jenkins-cicd-demo'
            TASKDEF_FILE='ecs_task_def.json'
            DESIRED_COUNT=1
            REPOSITORY_NAME='avv-jenkins-cicd-demo'
            REPOSITORY_URI="'${AWS_ACCOUNT}'.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY_NAME"
    }
    agent any
    stages {
        stage('Build') {
            steps {
                sh '''
                    cd jenkins-cicd/
                    echo "Building the cicd demo ngnix docker image.."
                    docker build -t "${SERVICE_NAME}" .
              '''  
            }
        }
        stage('Test') {
            steps {
               sh '''
                echo 'Code Quality and Code Security Testing using Sonarqube.. '
                echo 'Testing in progress..'
                echo 'The deployment would be failing at this stage if any codequality issues or vulnerability is detected in the code'
             '''
            }
        }
        stage('Deploy') {
            steps {
              sh '''
                echo 'Deploying to Amazon ECS....'
                docker tag ${SERVICE_NAME}:latest ${REPOSITORY_URI}:latest
                docker push ${REPOSITORY_URI}:latest
                echo 'Setting desired container count to 0'
                aws ecs update-service --cluster ${CLUSTER} --service ${SERVICE_NAME} --task-definition ${TASKDEF_NAME} --desired-count 0
                echo 'Updating task definition'
                aws ecs register-task-definition --cli-input-json file://${TASKDEF_FILE}
                echo 'Deploying to ECS Cluster: ${CLUSTER}'
                aws ecs update-service --cluster ${CLUSTER} --service ${SERVICE_NAME} --task-definition ${TASKDEF_NAME} --desired-count ${DESIRED_COUNT} --force-new-deployment
              '''
            }
        }
    }
}
